name: iOS Build with Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Create Config file with Secret
      run: |
        echo "API_KEY_VALUE = ${{ secrets.API_KEY_VALUE }}" > Config.xcconfig
        echo "Config.xcconfig dosyası oluşturuldu!"
    
    - name: Show Config (Secret gizlenecek)
      run: |
        echo "Config içeriği:"
        cat Config.xcconfig
    
    - name: Build iOS App
      run: |
        xcodebuild -project SecretDemo.xcodeproj \
                   -scheme SecretDemo \
                   -sdk iphonesimulator \
                   -configuration Debug \
                   -derivedDataPath ./build \
                   -xcconfig Config.xcconfig \
                   build
    
    - name: Create IPA (Simulator Build)
      run: |
        cd build/Build/Products/Debug-iphonesimulator
        mkdir Payload
        cp -R SecretDemo.app Payload/
        zip -r SecretDemo-Simulator.ipa Payload
        cd -
        cp build/Build/Products/Debug-iphonesimulator/SecretDemo-Simulator.ipa .
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SecretDemo-Build
        path: |
          SecretDemo-Simulator.ipa
          build/Build/Products/Debug-iphonesimulator/SecretDemo.app
        retention-days: 7
        