name: iOS Build with Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Create Config file with Secret
      run: |
        echo "API_KEY_VALUE = ${{ secrets.API_KEY_VALUE }}" > Config.xcconfig
        echo "Config.xcconfig dosyası oluşturuldu!"
    
    - name: Show Config (Secret gizlenecek)
      run: |
        echo "Config içeriği:"
        cat Config.xcconfig
    
    - name: Build iOS App
      run: |
        xcodebuild -project SecretDemo.xcodeproj \
                   -scheme SecretDemo \
                   -sdk iphonesimulator \
                   -configuration Debug \
                   -xcconfig Config.xcconfig \
                   build
    